

title: "Silver Leaf University â€“ Faculty & Student Portal"
logo: /assets/Logo.png
theme: minima

minima:
  skin: classic  

header_pages:
  - index.md

markdown: kramdown
kramdown:
  input: GFM

# Ensure assets load correctly
include:
  - assets
