theme: jekyll-theme-slate
title: "Silver Leaf University â€“ Faculty & Student Portal"
logo: /assets/Logo.png
header_pages:
  - index.md
  - problem.md
  - insights.md
  - solution.md
  - architecture.md
  - data.md
  - dashboard.md
  - ethics.md
  - outcomes.md
  - team.md
